### ISSUE TITLE
DNS Object Problems

### ISSUE THREAD

**Issue by Rhynorater** [ReconJSON/ReconJSON#11]
## Description
The DNS object needs to be able to describe all of the types of DNS Records. The definition should also be more clear and reflect the protocol. See the following examples:

```
"A":[{"example.acme.com":"54.0.0.1"}],
"CNAME":[{"example.acme.com":"example.prod.acme.com"}],
"AAAA":[{"example.acme.com":"FE80::1"}],
etc...
```

Each of these types of records should have an object definition.

**Comment by codingo** [comment]
I believe ports will have similar considerations, see #12.
