### ISSUE TITLE
Attribute: Ports (TCP:UDP)

### ISSUE THREAD

**Issue by codingo** [ReconJSON/ReconJSON#12]
For history, hosts are currently described with the following:

> [
> 	{
> 		"type":"Host",
> 		"fqdn":"example.acme.com",
> 		"ip":"192.168.0.1",
> 		"domain":"acme.com",
> 		"company":"Acme",
> 		"dns":{...},
> 		"ports":{...}
> 	}
> ]

This doesn't take into account TCP/UDP for ports. I believe a lot of authors would review the ports element and assume it to be a series of integers. Should we address tcp/udp more directly in the object?

**Comment by Rhynorater** [comment]
Yep. Thaaaat's probably a good idea :P 
My thoughts on how to do that would look like this:
```
"ports":{
    "tcp":{...},
    "udp":{...}
}
```
Both TCP and UDP MUST be defined within the structure of the ```ports``` attribute - even if they are empty. 

Thoughts?

**Comment by Rhynorater** [comment]
Resolved.
