### ISSUE TITLE
Use single backticks for inline code/pre

### ISSUE THREAD

**Issue by 0xdevalias** [ReconJSON/ReconJSON#17]
I noticed while skimming through the main code that triple backticks ``` are used wherever a code/pre is wanted, but this is only required for multiline blocks. When using inline, single backticks are sufficient `.

eg. This will use `inline code` whereas the following should use the triple backticks:

```
An example of triple backtick usage
```

I didn't bother changing/sending a PR as it might mess up any other currently pending PR's, but it would make the raw markdown much nicer/easier to read.

**Comment by Rhynorater** [comment]
@0xdevalias Great thoughts. I didn't realize you could just use single backticks for that. That is helpful.

I'm gonna put this one on the backburner for now (unless you wanna fix it yourself, which would be great) until we get the standard more fully developed. However, when its at a more stable point, I'll certainly go back and fix all of it.

**Comment by 0xdevalias** [comment]
Sounds good. Shall leave this open for a future reminder and handle it then.

**Comment by codingo** [comment]
I'm going to take care of this. May be a  few days, feel free to nudge me here if not committed by the 1st.
