### ISSUE TITLE
Sorting of data within arrays

### ISSUE THREAD

**Issue by 0xdevalias** [ReconJSON/ReconJSON#18]
Where the standard enforces an 'array-like' data type (eg. DNS TXT records), should the standard dictate if/how that array should be sorted? For example, alphabetical or otherwise for each section.

And if so, is this a `MUST` or a `SHOULD`? If not, should we make some distinction that the data contained within should be treated as unsorted and left up to the consumer to interpret?

**Comment by Rhynorater** [comment]
Great point. I'm thinking that it SHOULD be sorted. Thoughts?

**Comment by 0xdevalias** [comment]
I like the idea of it being sorted for consistency.. but if it's a `SHOULD` then downstream you can never trust that it will be, so will likely have to check/sort it anyway. And if you you have it is `MUST`/`SHOULD` then you would potentially have to get into defining how it is sorted/etc.. which might just needlessly complicate things..

**Comment by Rhynorater** [comment]
Yeah, I think its gonna be too messy to have to define how everything should be sorted. Let's just do a SHOULD with alphabetically and maybe someone will use it someday. Otherwise, I don't think its terribly important. 

Go ahead and close this if you agree.

**Comment by Rhynorater** [comment]
Done
