### ISSUE TITLE
Adopt a strict output format with a prototype

### ISSUE THREAD

**Issue by Ice3man543** [ReconJSON/ReconJSON#3]
## Overview

The format is currently very loosely based and can be mis-interpreted by different authors of open source tool. In my opinion the specification should be very clear and not misleading on any point. So, as i like open source, here is my contribution in the form of a complete structural detail on this Output format.

## Structure

The data is stored in a jsonlines file. The extension for jsonlines file is .jsonl. Then name of the jsonl file can be any generic name. Each line inside the jsonl file is at the highest level interpreted as a generic object and we assume no specific category as to whether it contains hosts or ips. The jsonlines file can be easily parsed in golang or any other language leading to an array of objects. This is where things get interesting.

Throughout this isssue, we will take an example output file called example.jsonl. At this point, the file has the following structure 
```
> cat example.jsonl
{object}
{object}
```
Each tool first takes a high level overview of the format without any details. Next, the task of parsing begins.

## Format Details

Each line is an object. At the bare minimum, each object needs to hold two data values, `type` and `version`. These are the mandatory values and it is required for a valid object to hold them. Without these, the object is considered invalid.

Details 
- `"type"` - type defines what kind of entity is this object representing - a host, an ip address, or something else. There are some predefined values which can be contained in a valid `type` object. The following are valid `type` values - `"host"`, `"ip"`. More can be added as required.
- `"version"` - version is the specification of the docs this file was made with. For the current one, it can be `"1.0.0"`.

The other values are intact as the original docs. 
For example this is a sample object 
```
{
    "type":"host",
    "version":"1.0.0",
    "subdomain":"example.acme.com",
    "ipv4":"192.168.0.1",
    "ipv6":"fe80::1",
    "domain":"acme.com",
    "company":"Acme",
    "dns":{...},
    "ports":{...}
}
```

For a value of `"host"` for type, the tool can assume that host can have either `"domain"` or `"subdomain"`  as key. It depends on what is present.

## Conclusion

The above presented idea is just a rough sketch. If anyone else has any additions or better ideas, do comment. 👍

**Comment by Ice3man543** [comment]
Also, @Rhyonater the specs need to define each field that may be present. This way developers can be free of worrying about not being compatible. Everything needs to be absolutely well defined and clear.

**Comment by Rhynorater** [comment]
I'll work on this. Especially about which fields are required by the respective objects.

**Comment by Rhynorater** [comment]
The "version" attribute will be added in at a later iteration. All other requests of this issue have been resolved.
