### ISSUE TITLE
Github organisation?

### ISSUE THREAD

**Issue by codingo** [ReconJSON/ReconJSON#4]
I greatly appreciate the first steps taken here @Rhynorater but here's a lot of interested parties / moving pieces to this to consider. I propose we move this project away from any one personal profile and convert to a Github organisation where this can be more properly managed.

The owners of tools looking at opting-in can be invited / made owners of the standard, jointly allowing for free collaboration and also to allow group consensus on the structure instead of any one person having the final say over how this will be structured.

Such an approach would also allow for more repositories associated with the idea allowing for sample usage in various languages to be demonstrated.

Thoughts?

**Comment by Ice3man543** [comment]
I agree with Michael here. It would allow far better collaboration and would allow it to hold multiple code examples in different languages. Also interested tool owners could probably work further on the format.

**Comment by Rhynorater** [comment]
@codingo It shall be done! I'll go ahead and work on that now.

**Comment by codingo** [comment]
Great, and for what it's worth I still believe any documentation should lead with your name having started this, even if multiple people co-author the organisation together.

What you've done here has needed to happen for a while, and is worthy of long-term recognition.

**Comment by Rhynorater** [comment]
@codingo Thanks for the consideration :) I appreciate that.

Just to update you, the hold up on starting an organization is creating the name :P If you have any suggestions, let me know hahaha

**Comment by Rhynorater** [comment]
Done. @codingo

**Comment by codingo** [comment]
Thank-you @Rhynorater. Could you also add some of the contributors to tools as admins on the organisation to keep it distributed? This would ensure its longevity.

I can vouch for @Ice3man543 @edoverflow @michenriksen.

**Comment by Rhynorater** [comment]
@codingo invites have been sent. Have you received yours?

**Comment by codingo** [comment]
Have now, thank-you! I've messaged you an e-mail on twitter for slack also.
