### ISSUE TITLE
Rename subdomain attribute

### ISSUE THREAD

**Issue by michenriksen** [ReconJSON/ReconJSON#9]
## Description 
The current example schema uses the attribute name `subdomain` for holding the FQDN for a host.

## Reasoning
A subdomain is only part of a host's FQDN and is therefore a little misleading and not flexible enough to accommodate tools that work with domain names, but not subdomain enumeration. An example would be something like a tool that finds live hosts in an IP range that might also want to provide reverse DNS information.

Renaming the attribute to something like `hostname` or `fqdn` would make the schema a bit more flexible.

**Comment by Rhynorater** [comment]
Agreed. Will make this change.

**Comment by Rhynorater** [comment]
Done.
